name: OpenVPN Connection - AutoTest

on:
  # workflow_dispatch:
  #   inputs:
  #     branch:
  #       description: 'Run tests on branch'
  #       required: true
  #       default: 'main'
  schedule:
  - cron: "00 18 * * *"
          
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install openvpn
    
    - name: Add certificates to client OVPN file and create client auth file
      run: |
        sed 's/REMOTE_IP_ADDRESS/${{ secrets.REMOTE_IP_ADDRESS }}/' client_template.ovpn > client.ovpn
        echo "${{ secrets.OVPN_CERTIFICATES }}" >> client.ovpn
        echo "${{ secrets.OVPN_CLIENT_CREDENTIAL }}" > client.auth
        
    - name: Connection OpenVPN
      run: |
        sudo openvpn --config client.ovpn&
        ./script/checkovpn.sh
        
